package org.pinguweb.backend.model.enums;

public enum TaskType {
    MEDICAL, SEARCH, SAFETY, LOGISTICS, COMMUNICATION, PSYCHOLOGICAL, FEED, MOBILITY, REFUGE, OTHER, PEOPLEMANAGEMENT, CLOTHING, BUILDING, CLEANING,
    FIREFIGHTERS, POLICE
}
